### ISSUE TITLE
My UW Font Awesome draconian widget style

### ISSUE THREAD

**Issue by smargovsky** [UWMadisonUcomm/uw-ui-toolkit#90]
Despite my flavor for the dramatic, the following style :

in src/less/uw-ui-toolkit/my-uw/widget.less
```less
.widget-body .fa {
  font-size:14px;
  padding:0px;
}
```
causes Font Awesome size classes ( fa-2x, etc ) to not be respected in widgets.  @timlevett, how does your circle button directive get around this?

Would removing this bit mess up other My UW widget styles?
